"""The interface the scheduler depends on, written down.

Two implementations of the KV core exist -- the Python reference and the C++17
extension -- and the scheduler must not be able to tell which it was handed.
That claim is worth more as a type than as a comment: ``build_kv`` is annotated
as returning these protocols, so if either implementation drifts from the
other's surface, mypy says so before a benchmark does.

They are deliberately narrow. Only what the scheduler actually calls belongs
here; a protocol that mirrored every method of the Python class would make the
extension's job "reimplement the reference" rather than "satisfy the
contract".
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Protocol, runtime_checkable

PrefixNode = Any
"""A handle to a cached prefix.

Deliberately opaque, and deliberately not a protocol. The Python cache hands
out its own ``Node`` and the C++ one hands out a generation-stamped
``NodeRef``; neither can accept the other's, and the contract the scheduler
actually honours is narrower than any shared type would express -- *hand back
the handle you were given, to the cache that gave it to you*. Writing that as
a structural type would claim an interchangeability that does not exist.
"""


class PrefixMatch(Protocol):
    @property
    def n_tokens(self) -> int: ...
    @property
    def block_ids(self) -> list[int]: ...
    @property
    def owner_seq(self) -> int: ...
    @property
    def hit(self) -> bool: ...
    @property
    def node(self) -> Any: ...


@runtime_checkable
class BlockPool(Protocol):
    """Paged KV block accounting."""

    @property
    def n_blocks(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    @property
    def n_copy_on_write(self) -> int: ...
    def free_blocks(self) -> int: ...
    def used_blocks(self) -> int: ...
    def blocks_needed(self, n_tokens: int, max_new_tokens: int, cached: int = 0) -> int: ...
    def initial_blocks(self, n_prompt_tokens: int, cached: int = 0) -> int: ...
    def alloc(self, n: int) -> list[int]: ...
    def share(self, block_ids: list[int]) -> None: ...
    def release(self, block_ids: list[int]) -> None: ...
    def is_shared(self, block_id: int) -> bool: ...
    def can_append(self, block_table: list[int], n_filled: int, n: int = 1) -> bool: ...
    def append_slot(self, block_table: list[int], n_filled: int) -> int | None: ...
    def fork_for_write(self, block_table: list[int], block_idx: int) -> int: ...
    def fragmentation_ratio(self, live_token_counts: list[int]) -> float: ...


class PrefixCache(Protocol):
    """The radix prefix cache.

    ``query_tokens`` and ``hit_tokens`` are writable on purpose: the scheduler
    matches a queued request on every step but advances the counters once, at
    admission, so that the reported hit rate is not weighted by how long a
    request waited.
    """

    on_seq_released: Callable[[int], None]
    query_tokens: int
    hit_tokens: int

    @property
    def hit_rate(self) -> float: ...
    def n_nodes(self) -> int: ...
    def match(self, token_ids: list[int], *, count: bool = True) -> PrefixMatch: ...
    def acquire(self, node: Any) -> None: ...
    def release(self, node: Any) -> None: ...
    def insert(self, token_ids: list[int], block_ids: list[int], owner_seq: int) -> Any: ...
    def evict(self, n_blocks_needed: int) -> int: ...
    def evict_nodes(self, n: int) -> int: ...
    def evict_all_unused(self) -> int: ...
