#!/usr/bin/env bash
# Regenerate everything the CI load gate compares against.
#
# Two artefacts, and the first one is the interesting part:
#
#   models/admission-ci-mock.pkl   a predictor and its conformal calibration,
#                                  fitted on the *mock* backend
#   bench/baselines/ci_baseline.json  the p99 and goodput the gate thresholds
#
# Why a second predictor exists at all
# ------------------------------------
# The gate runs the whole stack, admission control included, because a gate
# that skips the differentiator does not guard it. But a split-conformal bound
# is only valid on data exchangeable with its calibration set, and
# models/admission.pkl was calibrated on llama.cpp with Metal. Pointed at the
# mock backend -- whose requests are several times faster -- it predicts
# multi-second latencies for sub-second work and refuses 100% of requests at
# zero offered load. That is not a bug in the controller; it is the guarantee
# behaving exactly as advertised on a distribution it was not given.
#
# So the mock backend gets its own calibration, collected the same way, and
# the gateway warns at start-up if either is used on the wrong backend
# (cadence.admission.conformal_controller).
#
# Run this on any machine: the mock backend's cost model is a fixed sleep, so
# the numbers it produces are a property of the scheduler rather than of the
# host. That is the same reason the gate can threshold them on a GitHub
# runner. Rerun it when the scheduler deliberately changes, and say in the
# commit message why the new numbers are the right ones.
set -euo pipefail
cd "$(dirname "$0")/.."

SLO="${SLO:-2.0}"
ALPHA="${ALPHA:-0.01}"
GATE_RATES="${GATE_RATES:-4,8}"
GATE_DURATION="${GATE_DURATION:-45}"
PORT="${PORT:-8305}"
# Around the mock backend's knee with the `ci` workload: goodput peaks near
# 6 rps, so this spans roughly a third of capacity to a third above it.
C_RATES="${C_RATES:-2,3,4,5,6,8}"
ROUNDS="${ROUNDS:-3}"

if [ "${SKIP_COLLECT:-0}" != "1" ]; then
    uv run bench/collect_traces.py --config continuous+cache --workload ci \
        --rates "$C_RATES" --rounds "$ROUNDS" --duration 45 \
        --warmup 10 --cooldown 3 --slo "$SLO" --port "$PORT" \
        --outdir results/ci_traces --set CADENCE_BACKEND=mock
fi

uv run bench/fit_predictor.py --traces results/ci_traces \
    --alpha "$ALPHA" --slo "$SLO" --drop-warmup 10 --split round \
    --out models/admission-ci-mock.pkl --outdir results/ci_fit

# The gate's own run, with the same flags the workflow uses, so the baseline
# is measured by the thing it will be compared against.
uv run bench/run_sweep.py \
    --config continuous+cache+admission \
    --rates "$GATE_RATES" --duration "$GATE_DURATION" --warmup 10 --cooldown 3 \
    --slo "$SLO" --seed 0 --workload ci --port "$PORT" \
    --set CADENCE_BACKEND=mock \
    --set CADENCE_ADMISSION_MODEL=models/admission-ci-mock.pkl \
    --out results/ci_gate/baseline.parquet

uv run bench/check_regression.py results/ci_gate/baseline.parquet \
    --baseline bench/baselines/ci_baseline.json --slo "$SLO" \
    --update-baseline --note "${NOTE:-regenerated by bench/ci_baseline.sh}"
