"""Type stubs for the C++17 KV core (``src/cpp``).

Hand-written rather than generated, because their job is not only to satisfy
mypy: they are the statement, in Python's own vocabulary, of what the
extension promises. The protocols in ``cadence.engine.kv.protocols`` are
checked against these, so a signature that drifts from the Python reference is
a type error rather than a runtime surprise.
"""

from collections.abc import Callable, Sequence

class BlockAllocator:
    def __init__(self, n_blocks: int, block_size: int = 16) -> None: ...
    @property
    def n_blocks(self) -> int: ...
    @property
    def block_size(self) -> int: ...
    @property
    def n_copy_on_write(self) -> int: ...
    @property
    def free(self) -> list[int]: ...
    @property
    def refcount(self) -> list[int]: ...
    def free_blocks(self) -> int: ...
    def used_blocks(self) -> int: ...
    def blocks_needed(self, n_tokens: int, max_new_tokens: int, cached: int = 0) -> int: ...
    def initial_blocks(self, n_prompt_tokens: int, cached: int = 0) -> int: ...
    def alloc(self, n: int) -> list[int]: ...
    def share(self, block_ids: Sequence[int]) -> None: ...
    def release(self, block_ids: Sequence[int]) -> None: ...
    def is_shared(self, block_id: int) -> bool: ...
    def refcount_of(self, block_id: int) -> int: ...
    def slots_in(self, block_table: list[int]) -> int: ...
    def can_append(self, block_table: list[int], n_filled: int, n: int = 1) -> bool: ...
    def fork_for_write(self, block_table: list[int], block_idx: int) -> int: ...
    def append_slot(self, block_table: list[int], n_filled: int) -> int | None: ...
    def fragmentation_ratio(self, live_token_counts: Sequence[int]) -> float: ...
    def snapshot(self) -> dict[str, int]: ...

class ContiguousBlockAllocator(BlockAllocator):
    def __init__(
        self, n_blocks: int, block_size: int = 16, reserve_tokens: int = 512
    ) -> None: ...
    @property
    def reserve_tokens(self) -> int: ...

class NodeRef:
    """A generation-stamped handle to a node in the tree.

    Every attribute except ``alive`` raises ``RuntimeError`` once the node has
    been evicted, rather than reading freed memory.
    """

    @property
    def owner_seq(self) -> int: ...
    @property
    def refs(self) -> int: ...
    @property
    def depth_tokens(self) -> int: ...
    @property
    def last_used(self) -> int: ...
    @property
    def is_leaf(self) -> bool: ...
    @property
    def alive(self) -> bool: ...

class Match:
    @property
    def n_tokens(self) -> int: ...
    @property
    def block_ids(self) -> list[int]: ...
    @property
    def node(self) -> NodeRef | None: ...
    @property
    def owner_seq(self) -> int: ...
    @property
    def hit(self) -> bool: ...

class RadixCache:
    def __init__(self, blocks: BlockAllocator, block_size: int = 16) -> None: ...
    on_seq_released: Callable[[int], None]
    query_tokens: int
    hit_tokens: int
    n_evictions: int
    @property
    def block_size(self) -> int: ...
    @property
    def blocks(self) -> BlockAllocator: ...
    @property
    def hit_rate(self) -> float: ...
    def n_nodes(self) -> int: ...
    def n_owned_sequences(self) -> int: ...
    def paths(self) -> list[list[int]]: ...
    def match(self, token_ids: Sequence[int], *, count: bool = True) -> Match: ...
    def acquire(self, node: NodeRef | None) -> None: ...
    def release(self, node: NodeRef | None) -> None: ...
    def insert(
        self, token_ids: Sequence[int], block_ids: Sequence[int], owner_seq: int
    ) -> NodeRef | None: ...
    def evict(self, n_blocks_needed: int) -> int: ...
    def evict_nodes(self, n: int) -> int: ...
    def evict_all_unused(self) -> int: ...

# Benchmark scaffolding; see bench/bench_core.py.
def _noop() -> None: ...
def _noop_gil_released() -> None: ...
def _consume_tokens(tokens: Sequence[int]) -> int: ...
